Language: python
python:
  - "3.6"
  - "3.5"

  - "pypy"

addons:
  apt:
    update: true
install:
 - pip install -r requirements.txt


script: python3.6 test.py

notifications:
  recipientes:
    - roberto.dalas@lendico.com.br
