deployment:
  production:
    branch: master
    commands:
      - docker-compose -f hobbyprojects-compose/production/docker-compose.yml up -d
      - docker images --no-trunc | grep none | awk '{print $3}' | xargs docker rmi
