
     deploy-job:
       docker:
         - image: convox/proxy
       working_directory: /tmp/my-project  
       steps:
         - run
             name: Deploy Master to GKE
             command: ./deploy.sh
               
    workflows:
      version: 2
      build-deploy:
        jobs:
          - build-job
          - deploy-job:
              requires:
                - build-job
              filters:
                branches:
                  only: master
                  
